alertmanager:
  # we're using grafana alerts for the time being
  enabled: false

server:
  image:
    repository: prom/prometheus
    tag: v2.13.1
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/auth-type: "basic"
      traefik.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
    hosts:
      - prometheus-sandbox.pennlabs.org
    tls:
      - secretName: pennlabs-org-tls
        hosts:
          - prometheus-sandbox.pennlabs.org

extraScrapeConfigs: |
  - job_name: traefik
    static_configs:
      - targets:
          - traefik-prometheus.kube-system:9100
