{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $releaseName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $releaseName }}-svc
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
