pull_request_rules:
  - name: automatic merge for CI config
    conditions:
      - author=dependabot[bot]
      - files=.github/cdk/package.json
      - check-success=Validate cdkactions manifests
      - base=master
    actions:
      merge:
        method: squash
