apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platform-platform
  namespace: default
  annotations:
    ingress.kubernetes.io/protocol: http
spec:
  rules:
  - host: platform-test.pennlabs.org
    http:
      paths:
      - backend:
          serviceName: platform-platform
          servicePort: 443
        path: /
status:
  loadBalancer: {}
