apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
{{- if .Values.staging }}
  namespace: staging
{{- end }}
  labels:
    name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: "worker"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENABLE_DB_WAL
              value: "false"
            - name: SIGNUPS_ALLOWED
              value: "false"
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.secretEnv }}
