sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  
ingress:
  enabled: true
  hosts:
    - grafana.pennlabs.org

admin:
  existingSecret: grafana
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: true
  type: statefulset
  size: 10Gi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
   default:
     node-exporter:
       gnetId: 1860
       revision: 15
       datasource: Prometheus