[project]
name = "team-sync-2"
version = "0.1.0"
description = "Sync team members between different platforms based on GitHub teams & google drive."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pygithub>=2.6.1",
]
