#!/bin/bash

set -euo pipefail

# Get current timestamp
STAMP=`date +"%Y%m%d - %A %d %B %Y @ %H:%M"`

# List all databases and remove default databases
DATABASES=`psql $DATABASE_URL/defaultdb -q -t -c 'SELECT datname from pg_database' | grep -v "\(_dodb\|template1\|template0\|defaultdb\)"`

echo "Starting backup"

# Dump each database and upload to S3
for DB in $DATABASES
do
  FILENAME="$STAMP - $DB.sql.gz"
  echo "Creating dump of $DB"
  pg_dump $DATABASE_URL/$DB | gzip > $DB.dump
  echo "Uploading dump of $DB"
  cat $DB.dump | aws s3 cp - "s3://$S3_BUCKET/$STAMP/$S3_PREFIX/$FILENAME"
done

echo "Backup finished successfully"
echo "Total data backed up: `du -hc *.dump | grep total | cut -f1`"
