apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wildcard-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@pennlabs.org
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector: {}
        dns01:
          route53:
            region: us-east-1
