apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations: 
    meta.helm.sh/release-name: pennlabs-wildcard-cert
    meta.helm.sh/release-namespace: default
  name: pennlabs-org
spec:
  secretName: pennlabs-org-tls
  dnsNames:
    - "pennlabs.org"
    - "*.pennlabs.org"
  issuerRef:
    name: wildcard-letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
