name: "Django"
description: "Test, lint, and upload code coverage for a django project. Built for internal use at Penn Labs."
author: "Penn Labs"
inputs:
  project-location:
    required: false
    description: Location of the django project. Defaults to .
    default: "."

  project-name:
    required: true
    description: Name of the django project. Required

  black:
    required: false
    description: Run black?
    default: "true"

  flake8:
    required: false
    description: Run flake8?
    default: "true"

runs:
  using: "composite"
  steps:
    - run: |
        pwd
        echo $INPUT_PROJECT_LOCACTION
        echo $INPUT_PROJECT-LOCACTION
        cd $INPUT_PROJECT-LOCACTION
        pwd
        sudo pip install pipenv
        pipenv install --deploy --dev
      shell: bash
