name: "Django"
description: "Test, lint, and upload code coverage for a django project. Built for internal use at Penn Labs."
author: "Penn Labs"
inputs:
  project-location:
    required: false
    description: Location of the django project. Defaults to .
    default: "."

  project-name:
    required: true
    description: Name of the django project. Required

  black:
    required: false
    description: Run black?
    default: "true"

  flake8:
    required: false
    description: Run flake8?
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        cd ${{ inputs.project-location }}
        pwd
        sudo pip install pipenv
        pipenv install --deploy --dev
      shell: bash
    - name: Lint (flake8)
      run: |
        pwd
        ${{ inputs.flake8 }} && pipenv run flake8 .
      shell: bash
    - name: Lint (black)
      run: |
        ${{ inputs.black }} && pipenv run black --check .
      shell: bash
