name: "Django"
description: "Test, lint, and upload code coverage for a django project. Built for internal use at Penn Labs."
author: "Penn Labs"
inputs:
  project-location:
    required: false
    description: Location of the django project. Defaults to .
    default: "."

  project-name:
    required: true
    description: Name of the django project. Required

  black:
    required: false
    description: Run black?
    default: "true"

  flake8:
    required: false
    description: Run flake8?
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        cd ${{ inputs.project-location }}
        sudo pip install pipenv
        pipenv install --deploy --dev
      shell: bash
    - name: Lint (flake8)
      run: |
        cd ${{ inputs.project-location }}
        ${{ inputs.flake8 }} && pipenv run flake8 .
      shell: bash
    - name: Lint (black)
      run: |
        cd ${{ inputs.project-location }}
        ${{ inputs.black }} && pipenv run black --check .
      shell: bash
    - name: Test
      run: |
        cd ${{ inputs.project-location }}
        pipenv run coverage run manage.py test --settings=${{ inputs.project-name }}.settings.ci
      shell: bash
    - name: Upload code coverage
      run: |
        echo "Need to add a root flag? TODO:"
        cd ${{ inputs.project-location }}
        pipenv run codecov --flags backend
      shell: bash
