global:
  image: "vault:1.2.2"

server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "postgresql" {
      }

      seal "awskms" {
        region     = "us-east-1"
      }

  dataStorage:
    enabled: false

  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: VAULT_AWSKMS_SEAL_KEY_ID
      secretName: vault
      secretKey: VAULT_AWSKMS_SEAL_KEY_ID
    - envName: VAULT_PG_CONNECTION_URL
      secretName: vault
      secretKey: VAULT_PG_CONNECTION_URL

  service:
    enabled: true

  ingress:
    enabled: true
    hosts:
      - host: vault.pennlabs.org
        paths: ["/"]
    tls:
      - hosts:
          - vault.pennlabs.org
        secretName: pennlabs-org-tls

ui:
  enabled: true
  serviceType: ClusterIP
