apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: temp-vault-ingress
  namespace: default
spec:
  rules:
    - host: vault.upenn.club
      http:
        paths:
          - backend:
              serviceName: vault
              servicePort: 8200
            path: /
