#!/bin/bash
set -e

# Start PostgreSQL service
sudo service postgresql start

# Start Redis server in the background
redis-server --daemonize yes

# PostgreSQL user and database details
PG_USER="postgres"
PG_PASSWORD="postgres"
PG_DATABASE="postgres"

# Alter the PostgreSQL user password
sudo -u postgres psql -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "$PG_DATABASE" <<-EOSQL
    ALTER USER $PG_USER WITH PASSWORD '$PG_PASSWORD';
EOSQL

# Create a new PostgreSQL user "penn-courses" with the same password if it doesn't already exist
sudo -u postgres psql -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "$PG_DATABASE" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'penn-courses') THEN
            CREATE USER "penn-courses" WITH PASSWORD '$PG_PASSWORD';
        END IF;
    END
    \$\$;
EOSQL

echo "PostgreSQL user password updated successfully."
