#!/bin/bash

declare -A PRODUCT_TO_SHA

# TODO: Add remaining products back since they aren't migrated to uv
PRODUCT_TO_SHA=(
  ["office-hours-queue"]="7fdcdaeba0b83600950edfbdfb155ba62cd2febd"
  ["penn-clubs"]="a69532b40c40c6ad0a2c6856e11034c70fbab26c"
  # ["penn-mobile"]="093a9f58ec7d778acc12dad40d0ece109e6346e8"
  ["penn-courses"]="b5cadf67f2924ed7ef77c59d81d3f08f9ebc05e0"
  # ["platform"]="022d2671a7811e8e2b6f772948ff28d18fa6422a"
)

# uv native installation using [uv sync]
for product in "${!PRODUCT_TO_SHA[@]}"; do
  sha="${PRODUCT_TO_SHA[$product]}"
  PRODUCT_PATH="/opt/waypoint/$product"
  BACKEND_BASE="https://raw.githubusercontent.com/pennlabs/$product/$sha/backend"

  echo "Installing dependencies for $product @ $sha with uv"
  mkdir -p "$PRODUCT_PATH"

  curl -o $PRODUCT_PATH/pyproject.toml "$BACKEND_BASE/pyproject.toml"
  curl -o $PRODUCT_PATH/uv.lock "$BACKEND_BASE/uv.lock"

  cd $PRODUCT_PATH
  uv sync --frozen --all-groups
done

echo "Setup complete!"
