exports.options = {
    repository: 'https://github.com/pennlabs/infrastructure.git',
    authorName: "Penn Labs",
    authorAddress: "contact@pennlabs.org",
    authorOrganization: 'Penn Labs',
    authorUrl: 'https://pennlabs.org',
    buildWorkflow: false,
    pullRequestTemplate: false,
    releaseWorkflow: false,
    dependabot: false,
    mergify: false,
    compat: false,
    dependabot: false,
    rebuildBot: false,
    clobber: false,
    docgen: true,
    docsDirectory: 'docs',
    license: 'MIT',
    licensed: true,
    gitignore: ['/docs'],
}
