---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: secret-sync
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-auth
          volumes:
            - name: vault-token
              emptyDir:
                medium: Memory
          restartPolicy: Never
          containers:
            - name: vault-kubernetes-authenticator
              image: postfinance/vault-kubernetes-authenticator:0.1.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: http://vault.default:8200
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_ROLE
                  value: secret-reader
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
                - name: ALLOW_FAIL
                  value: "true"
            - name: vault-kubernetes-synchronizer
              image: postfinance/vault-kubernetes-synchronizer:0.1.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: http://vault.default:8200
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
                - name: SECRET_PREFIX
                  value: ""
                - name: VAULT_SECRETS
                  value: secrets/
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: secret-sync
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-auth
          volumes:
            - name: vault-token
              emptyDir:
                medium: Memory
          restartPolicy: Never
          containers:
            - name: vault-kubernetes-authenticator
              image: postfinance/vault-kubernetes-authenticator:0.1.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: http://vault.default:8200
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_ROLE
                  value: secret-reader
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
                - name: ALLOW_FAIL
                  value: "true"
            - name: vault-kubernetes-synchronizer
              image: postfinance/vault-kubernetes-synchronizer:0.1.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vault-token
                  mountPath: /home/vault/
              env:
                - name: VAULT_ADDR
                  value: http://vault.default:8200
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_TOKEN_PATH
                  value: /home/vault/.vault-token
                - name: SECRET_PREFIX
                  value: ""
                - name: VAULT_SECRETS
                  value: secrets/
