# STAGING NS
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: staging

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin-rolebinding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: staging
roleRef:
  kind: Role
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: staging

# DEFAULT NA
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-admin-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default
roleRef:
  kind: Role
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default