global:
  image: "vault:1.2.2"

server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "mysql" {
        username = "$VAULT_DB_USER"
        password = "$VAULT_DB_PASSWORD"
        database = "$VAULT_DB_NAME"
        address = "$VAULT_DB_HOST:$VAULT_DB_PORT"
      }

      seal "awskms" {
        region     = "us-east-1"
        kms_key_id = "$KMS_KEY_ID"
      }

  dataStorage:
    enabled: false

  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-secrets
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-secrets
      secretKey: AWS_SECRET_ACCESS_KEY

  service:
    enabled: true

ui:
  enabled: true
  serviceType: ClusterIP
