apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault
spec:
  rules:
  - host: vault.pennlabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: vault-ui
          servicePort: 8200
