replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

extraEnv: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]
