name: Publish waypoint
on:
  push:
    paths:
      - docker/waypoint/**

jobs:
  publish-waypoint:
    name: Publish waypoint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          image: tonistiigi/binfmt:latest
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-publish-waypoint
      # Only log in to Docker Hub if pushing to master
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build the Docker image but don't push if not on master
      - name: Build/Publish (Dry Run)
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/master'
        with:
          context: docker/waypoint
          file: docker/waypoint/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/waypoint:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            pennlabs/waypoint:latest
            pennlabs/waypoint:${{ github.sha }}
      - name: Build/Publish
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          context: docker/waypoint
          file: docker/waypoint/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/waypoint:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            pennlabs/waypoint:latest
            pennlabs/waypoint:${{ github.sha }}
