name: Publish pg-s3-backup
on:
  push:
    branches:
      - master
    paths:
      - "docker/pg-s3-backup/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish pg-s3-backup
        uses: docker/build-push-action@v1
        with:
          repository: pennlabs/pg-s3-backup
          path: docker/pg-s3-backup
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ github.sha }}"
