name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            binary_suffix: ""
          - os: macos-latest
            arch: arm64
            binary_suffix: "-arm64"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller
          cd docker/waypoint && pip install .
          
      - name: Build binary
        working-directory: docker/waypoint
        run: pyinstaller src/waypoint_client.py --onefile --name "waypoint-client${{ matrix.binary_suffix }}"
          
      - name: Calculate SHA256
        run: |
          cd docker/waypoint/dist
          echo "BINARY_SHA=$(sha256sum waypoint-client${{ matrix.binary_suffix }} | awk '{print $1}')" >> $GITHUB_ENV
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: docker/waypoint/dist/waypoint-client*
          name: Release ${{ github.ref_name }}
          body: |
            SHA256 (${{ matrix.os }}-${{ matrix.arch }}): ${{ env.BINARY_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}