name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            binary_suffix: "-linux-x86_64"
          - os: macos-latest
            arch: x86_64
            binary_suffix: "-macos-x86_64"
          - os: macos-latest
            arch: arm64
            binary_suffix: "-macos-arm64"

    runs-on: ${{ strategy.matrix.os }}
    outputs:
      sha_${{ matrix.os }}_${{ matrix.arch }}: ${{ env.BINARY_SHA }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          cd docker/waypoint && pip install .

      - name: Build binary
        working-directory: docker/waypoint
        run: pyinstaller src/waypoint_client.py --onefile --name "waypoint-client${{ matrix.binary_suffix }}"

      - name: Calculate SHA256
        run: |
          cd docker/waypoint/dist
          echo "BINARY_SHA=$(sha256sum waypoint-client${{ matrix.binary_suffix }} | awk '{print $1}')" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: waypoint-client${{ matrix.binary_suffix }}
          path: docker/waypoint/dist/waypoint-client${{ matrix.binary_suffix }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          name: Release ${{ github.ref_name }}
          body: |
            SHA256 Checksums:
            - Linux (x86_64): ${{ needs.build.outputs.sha_ubuntu-latest_x86_64 }}
            - macOS (x86_64): ${{ needs.build.outputs.sha_macos-latest_x86_64 }}
            - macOS (arm64): ${{ needs.build.outputs.sha_macos-latest_arm64 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
