name: Release

on:
  push:
    # TODO: TEMP, do not commit this. just to trigger the workflow.
    paths:
      - 'docker/waypoint/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller
          cd docker/waypoint && pip install .
          
      - name: Build binary
        working-directory: docker/waypoint
        run: pyinstaller src/waypoint_client.py --onefile --name waypoint-client
          
      - name: Calculate SHA256
        run: |
          cd docker/waypoint/dist
          echo "BINARY_SHA=$(sha256sum waypoint-client | awk '{print $1}')" >> $GITHUB_ENV
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: docker/waypoint/dist/waypoint-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
