applications:
  - name: bitwarden
    image: bitwardenrs/server-postgresql
    tag: "1.16.3"
    secret: bitwarden
    ingress:
      hosts:
        - host: bitwarden.pennlabs.org
          paths: ["/"]
    extraEnv:
      - name: SIGNUPS_ALLOWED
        value: "false"
      - name: ENABLE_DB_WAL
        value: "false"
