installCRDs: true

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::449445102765:role/cert-manager

#securityContext:
#  enabled: true
#  fsGroup: 1001

global:
  imagePullSecrets:
    - name: docker-pull-secret
