installCRDs: true

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${roleARN}

securityContext:
  enabled: true
  fsGroup: 1001

global:
  imagePullSecrets:
    - name: docker-pull-secret
      
podAnnotations:
  ad.datadoghq.com/cert-manager.check_names: '["cert_manager"]'
  ad.datadoghq.com/cert-manager.init_configs: '[{}]'
  ad.datadoghq.com/cert-manager.instances: |
    [
      {
        "prometheus_url": "http://%%host%%:9402/metrics"
      }
    ]   

webhook:
  podAnnotations:
    ad.datadoghq.com/cert-manager-webhook.check_names: '["cert_manager"]'
    ad.datadoghq.com/cert-manager-webhook.init_configs: '[{}]'
    ad.datadoghq.com/cert-manager-webhook.instances: |
      [
        {
          "prometheus_url": "http://%%host%%:9402/metrics"
        }
      ]   

cainjector:
  podAnnotations:
    ad.datadoghq.com/cert-manager-cainjector.check_names: '["cert_manager"]'
    ad.datadoghq.com/cert-manager-cainjector.init_configs: '[{}]'
    ad.datadoghq.com/cert-manager-cainjector.instances: |
      [
        {
          "prometheus_url": "http://%%host%%:9402/metrics"
        }
      ]   
  