datadog:
  # datadog.apiKeyExistingSecret -- Use existing Secret which stores API key instead of creating a new one. The value should be set with the `api-key` key inside the secret.
  ## If set, this parameter takes precedence over "apiKey".
  apiKeyExistingSecret: datadog

  ## Enable logs agent and provide custom configs
  logs:
    # datadog.logs.enabled -- Enables this to activate Datadog Agent log collection
    ## ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    enabled: true

    # datadog.logs.containerCollectAll -- Enable this to allow log collection for all containers
    ## ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    containerCollectAll: true

  confd:
    cert_manager.yaml: |-
      ad_identifiers:
        - cert-manager
      init_config:
      instances:
        - prometheus_url: http://%%host%%:9402/metrics

agents:
  image:
   repository: pennlabs/datadog-agent
   tag: 7479c2dd283d4ecc808fc65107048658dde778a2
   doNotCheckTag: true
