cronjobs:
  - name: db-backup
    schedule: "21 2 * * *"
    secret: db-backup
    image: pennlabs/pg-s3-backup
    tag: 18806efdf96777fce2341b8eb81c95bf1a7d6897
    extraEnv:
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

rbac:
  createSA: true
  roleARN: ${roleARN}
