image:
  repository: renovate/renovate
  tag: 24.89.3

cronjob:
  schedule: "0 * * * *"

renovate:
  # See https://docs.renovatebot.com/self-hosted-configuration
  config: |
    {
      "autodiscover": false,
      "autodiscoverFilter": "pennlabs/*",
      "printConfig": true,
      "allowedPostUpgradeCommands": ["cd .github/cdk && yarn build"],
      "trustLevel": "high",
      "gitAuthor": "Renovate Bot <githubbot@pennlabs.org>",
      "repositories": ["pennlabs/infrastructure", "pennlabs/platform"]
    }

existingSecret: "renovate"

redis:
  enabled: true
