cronjobs:
  - name: team-sync
    schedule: "*/10 * * * *"
    secret: team-sync
    image: pennlabs/team-sync
    tag: d6cdea59a93adb81d26053049c82ae9f5f5779ae
    failureLimit: 1
    extraEnv:
      - name: VAULT_ADDR
        value: https://vault.pennlabs.org
      - name: PLATFORM_URL
        value: https://platform.pennlabs.org

rbac:
  createSA: true
  roleARN: ${roleARN}
