cronjobs:
  - name: team-sync
    schedule: "*/10 * * * *"
    secret: team-sync
    image: pennlabs/team-sync
    tag: 20fd985ea8627e43d12387a44443f75e4b99bda8
    extraEnv:
      - name: VAULT_ADDR
        value: https://vault.pennlabs.org
      - name: PLATFORM_URL
        value: https://platform.pennlabs.org

rbac:
  createSA: true
  roleARN: ${roleARN}
