cronjobs:
  - name: team-sync
    schedule: "*/10 * * * *"
    secret: team-sync
    image: pennlabs/team-sync
    tag: 98bd93b34e2269d3d9d534f05fb8d170077eeb32
    extraEnv:
      - name: VAULT_ADDR
        value: https://vault.pennlabs.org

rbac:
  createSA: true
  roleARN: ${roleARN}
