cronjobs:
  - name: team-sync
    schedule: "*/10 * * * *"
    secret: team-sync
    image: pennlabs/team-sync
    tag: 68536ae854d0c70e8e4e40c889c2423b1da44461
    failureLimit: 1
    extraEnv:
      - name: VAULT_ADDR
        value: https://vault.pennlabs.org
      - name: PLATFORM_URL
        value: https://platform.pennlabs.org

rbac:
  createSA: true
  roleARN: ${roleARN}
