deployment:
  replicas: 2
  imagePullSecrets:
    - name: dockerPullSecret
  podAnnotations:
    ad.datadoghq.com/traefik.check_names: |
      ["openmetrics"]
    ad.datadoghq.com/traefik.init_configs: |
      [{}]
    ad.datadoghq.com/traefik.instances: |
      [
        {
          "openmetrics_endpoint": "http://%%host%%:9100/metrics",
          "namespace": "traefik",
          "metrics": [".*"],
          "max_returned_metrics": 3000
        }
      ]

logs:
  general:
    access:
      enabled: true